apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: quay.io/jetstack/charts
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: crds.enabled
          value: 'true'
  sources: []
  project: core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - CreateNamespace=true
